<div class="form-group">
    <label class="form-label" style="font-weight: 400;color: #aaa;"><?= __('Language') ?></label>
    <select class="form-control" data-live-search="true" name="language">
        <option value="English" selected="selected">English</option>
        <option>Afrikaans</option>
        <option>Albanian</option>
        <option>Amharic</option>
        <option>Arabic</option>
        <option>Armenian</option>
        <option>Azerbaijani</option>
        <option>Basque</option>
        <option>Belarusian</option>
        <option>Bengali</option>
        <option>Bosnian</option>
        <option>Bulgarian</option>
        <option>Burmese</option>
        <option>Catalan</option>
        <option>Cebuano</option>
        <option>Chichewa</option>
        <option>Chinese_simplified</option>
        <option>Chinese_traditional</option>
        <option>Corsican</option>
        <option>Croatian</option>
        <option>Czech</option>
        <option>Danish</option>
        <option>Dutch</option>
        <option>English</option>
        <option>Esperanto</option>
        <option>Estonian</option>
        <option>Farsi</option>
        <option>Filipino</option>
        <option>Finnish</option>
        <option>French</option>
        <option>Frisian</option>
        <option>Galician</option>
        <option>Georgian</option>
        <option>German</option>
        <option>Greek</option>
        <option>Gujarati</option>
        <option>Haitian Creole</option>
        <option>Hausa</option>
        <option>Hawaiian</option>
        <option>Hebrew</option>
        <option>Hindi</option>
        <option>Hmong</option>
        <option>Hungarian</option>
        <option>Icelandic</option>
        <option>Igbo</option>
        <option>Indonesian</option>
        <option>Irish</option>
        <option>Italian</option>
        <option>Japanese</option>
        <option>Javanese</option>
        <option>Kannada</option>
        <option>Kazakh</option>
        <option>Khmer</option>
        <option>Korean</option>
        <option>Kurdish</option>
        <option>Kyrgyz</option>
        <option>Lao</option>
        <option>Latin</option>
        <option>Latvian</option>
        <option>Lithuanian</option>
        <option>Luxembourgish</option>
        <option>Macedonian</option>
        <option>Malagasy</option>
        <option>Malay</option>
        <option>Malayalam</option>
        <option>Maltese</option>
        <option>Maori</option>
        <option>Marathi</option>
        <option>Mongolian</option>
        <option>Nepali</option>
        <option>Norwegian</option>
        <option>Pashto</option>
        <option>Persian</option>
        <option>Polish</option>
        <option>Portuguese</option>
        <option>Punjabi</option>
        <option>Romanian</option>
        <option>Russian</option>
        <option>Samoan</option>
        <option>Scots Gaelic</option>
        <option>Serbian</option>
        <option>Sesotho</option>
        <option>Shona</option>
        <option>Sindhi</option>
        <option>Sinhala</option>
        <option>Slovak</option>
        <option>Slovenian</option>
        <option>Somali</option>
        <option>Spanish</option>
        <option>Sundanese</option>
        <option>Swahili</option>
        <option>Swedish</option>
        <option>Tajik</option>
        <option>Tamil</option>
        <option>Telugu</option>
        <option>Thai</option>
        <option>Turkish</option>
        <option>Ukrainian</option>
        <option>Urdu</option>
        <option>Uzbek</option>
        <option>Vietnamese</option>
        <option>Welsh</option>
        <option>Xhosa</option>
        <option>Yiddish</option>
        <option>Yoruba</option>
        <option>Zulu</option>
    </select>
</div>